Transifex
1hostjs/hosting pull request #29
Opened 2021-04-09 17:36 UTC by GrahamSH-LLK

**Resolves**

Resolves #

**Changes**

**Reason for changes**

**Tests**

2021-04-09 19:54 UTC, wgyt approved these changes

2021-04-09 19:56 UTC, wgyt commented
@GrahamSH-LLK you can merge this if you want

2021-04-09 21:05 UTC, GrahamSH-LLK commented
This needs more extensive testing to make sure I didn't break anything

2021-04-09 21:31 UTC, thecoder876 approved these changes
seems fine, ready to merge after testing (marked as draft because it isn't ready yet)

2021-04-09 21:32 UTC, wgyt commented
> This needs more extensive testing to make sure I didn't break anything

Go ahead and test it

2021-04-09 21:33 UTC, GrahamSH-LLK commented
> > This needs more extensive testing to make sure I didn't break anything
> 
> Go ahead and test it

Go test it yourself, I'm going outside.

2021-04-09 21:33 UTC, thecoder876 commented
> > > This needs more extensive testing to make sure I didn't break anything
> > 
> > 
> > Go ahead and test it
> 
> Go test it yourself, I'm going outside.

lol

2021-04-09 21:50 UTC, thecoder876 requested changes

2021-04-09 21:50 UTC, thecoder876 commented on localization/strings.en.js
> +t("✖ 1host.js Fatal Error");
```suggestion
t("1Host.js Success");
t("1Host.js Warning");
t("1Host.js Error");
t("1Host.js Fatal Error");
```
@GrahamSH-LLK pls remove emojis and capitalize "1host"

2021-04-09 21:53 UTC, wgyt commented on localization/strings.en.js
> +t("✖ 1host.js Fatal Error");
@thecoder876 this is intended

2021-04-09 21:53 UTC, GrahamSH-LLK commented on localization/strings.en.js
> +t("✖ 1host.js Fatal Error");
A. the emojis are cool
B. it's 1host, not 1Host

2021-04-11 12:20 UTC, thecoder876 commented on localization/strings.en.js
> +t("✖ 1host.js Fatal Error");
> [ping removed] this is intended

@wgyt oh ok

2021-04-11 12:21 UTC, thecoder876 approved these changes
approved (again)

2021-04-11 12:51 UTC, thecoder876 commented
finished with testing?

2021-04-11 15:05 UTC, merged