1host.js CLI
1hostjs/hosting pull request #64
Opened 2021-04-18 13:35 UTC by wgyt

**Resolves**

Resolves #57

**Changes**

Added more cli comments

**Reason for changes**

Better cli that makes life easier

**Tests**

none, yet.

2021-04-18 14:09 UTC, wgyt commented
This is almost done 🎉
I just need to make adding modules possible, right now it is a todo

2021-04-18 14:43 UTC, GrahamSH-LLK requested changes

2021-04-18 14:43 UTC, GrahamSH-LLK commented on bin/help.mjs
> +        `,
Put this in strings

2021-04-18 14:43 UTC, GrahamSH-LLK commented on bin/config.mjs
> +    `module.exports={port:${portt},modules:${modules}}`,
It should read the json and change it using JS

2021-04-18 14:49 UTC, wgyt commented on bin/config.mjs
> +    `module.exports={port:${portt},modules:${modules}}`,
Right now it only makes the config file :\ but I guess I could change it

2021-04-18 14:49 UTC, wgyt commented on bin/help.mjs
> +        `,
how do I do that?

2021-04-18 17:36 UTC, wgyt commented
the config utility is almost done but it won't work with modules yet, but we give instructions. To be fair we warn them so
🤷🏻‍♂️

2021-04-18 17:56 UTC, retronbv requested changes
> the config utility is almost done but it won't work with modules(fully) yet

Fix that then it’s good

2021-04-18 18:27 UTC, wgyt commented
> > the config utility is almost done but it won't work with modules(fully) yet
> 
> Fix that then it’s good

Can you fix it? I wasnt able to get it to work :(

2021-04-18 21:57 UTC, wgyt commented
@GrahamSH-LLK I figured out how it broke, it executes the code after the function while the function is running 🐢

2021-04-19 11:19 UTC, retronbv commented
> > > the config utility is almost done but it won't work with modules(fully) yet
> > 
> > 
> > Fix that then it’s good
> 
> Can you fix it? I wasnt able to get it to work :(

I don’t do that kind of stuff

2021-04-20 15:13 UTC, wgyt commented
@retronbv @GrahamSH-LLK IT WORKS!!!! LETS GOOOOOOOOOO

2021-04-20 15:22 UTC, merged